name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pre-commit
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Tests
        run: bazel test //...
